-- H2 本地文件数据库初始化脚本。F1 在此基础上补充业务表。
CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

-- ============================================================
-- 古籍修复工序与纸张状态追踪模块
-- 业务键：馆藏册号 + 修复版本唯一；各单据号唯一
-- 审计列：request_no / operator / biz_timezone / version_snapshot
-- 快照列：检测、工序、验收均保留 paper_snapshot 纸张状态快照
-- ============================================================

-- 馆藏册（修复对象）
CREATE TABLE IF NOT EXISTS t_archive_volume (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volume_no VARCHAR(32) NOT NULL,
    restore_version VARCHAR(16) NOT NULL,
    title VARCHAR(128) NOT NULL,
    paper_type VARCHAR(64),
    status VARCHAR(16) NOT NULL,
    moisture_content DECIMAL(6,2),
    ph_value DECIMAL(4,2),
    fiber_strength DECIMAL(10,2),
    received_date DATE NOT NULL,
    request_no VARCHAR(64),
    operator VARCHAR(64),
    biz_timezone VARCHAR(64),
    version_snapshot VARCHAR(2000),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_volume_biz UNIQUE (volume_no, restore_version)
);

-- 修复批次
CREATE TABLE IF NOT EXISTS t_restore_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(32) NOT NULL,
    batch_name VARCHAR(128),
    status VARCHAR(16) NOT NULL,
    biz_date DATE NOT NULL,
    request_no VARCHAR(64),
    operator VARCHAR(64),
    biz_timezone VARCHAR(64),
    version_snapshot VARCHAR(2000),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_batch_no UNIQUE (batch_no)
);

-- 批次-馆藏册关联
CREATE TABLE IF NOT EXISTS t_batch_volume (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    volume_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_batch_volume UNIQUE (batch_id, volume_id)
);

-- 修复工单（工序载体，完工时保留纸张状态快照）
CREATE TABLE IF NOT EXISTS t_restore_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL,
    batch_id BIGINT NOT NULL,
    volume_id BIGINT NOT NULL,
    process_name VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL,
    work_hours DECIMAL(8,2),
    start_date DATE,
    finish_date DATE,
    paper_snapshot VARCHAR(2000),
    request_no VARCHAR(64),
    operator VARCHAR(64),
    biz_timezone VARCHAR(64),
    version_snapshot VARCHAR(2000),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_order_no UNIQUE (order_no)
);

-- 检测样本（含水率/酸碱度/纤维强度 + 纸张状态快照）
CREATE TABLE IF NOT EXISTS t_inspect_sample (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    volume_id BIGINT NOT NULL,
    moisture_content DECIMAL(6,2) NOT NULL,
    ph_value DECIMAL(4,2) NOT NULL,
    fiber_strength DECIMAL(10,2) NOT NULL,
    inspect_date DATE NOT NULL,
    paper_snapshot VARCHAR(2000) NOT NULL,
    request_no VARCHAR(64),
    operator VARCHAR(64),
    biz_timezone VARCHAR(64),
    version_snapshot VARCHAR(2000),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_sample_no UNIQUE (sample_no)
);

-- 验收记录（验收结论 + 纸张状态快照；已签发报告不可直接删除）
CREATE TABLE IF NOT EXISTS t_accept_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accept_no VARCHAR(32) NOT NULL,
    order_id BIGINT NOT NULL,
    volume_id BIGINT NOT NULL,
    result VARCHAR(16) NOT NULL,
    accept_date DATE NOT NULL,
    report_issued BOOLEAN NOT NULL DEFAULT FALSE,
    paper_snapshot VARCHAR(2000) NOT NULL,
    request_no VARCHAR(64),
    operator VARCHAR(64),
    biz_timezone VARCHAR(64),
    version_snapshot VARCHAR(2000),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_accept_no UNIQUE (accept_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('restore-1', '古籍修复工序与纸张状态追踪模块');
